# Generated by Django 5.1.7 on 2025-04-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questionQuiz", models.CharField(max_length=100)),
                ("bonneReponse", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ReponseUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reponseUtilisateur", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("debutQuiz", models.BooleanField(default=False)),
                (
                    "prompt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="prompts.prompt"
                    ),
                ),
            ],
        ),
    ]
