# Generated by Django 5.1.7 on 2025-04-17 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scenario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariolance",
            name="utilisateur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenarioDispo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reponseutilisateur",
            name="scenario_lance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reponses_utilisateur",
                to="scenario.scenariolance",
            ),
        ),
    ]
