# Generated by Django 5.1.7 on 2025-04-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("contenue", models.CharField(max_length=120)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ManyToManyField(
                        blank=True, related_name="workspaces", to="documents.document"
                    ),
                ),
            ],
        ),
    ]
